services:
  - type: web
    name: ffwc-waterlevel-multi  # use a unique name if reusing this separately
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
